### PR TITLE
Made node content available to look at, encase someone needs to send a particular nodes conent around over a network they now have access to it

### PR DESCRIPTION
**Pull request by tymerica**

### CODE REVIEW

**Comment by tymerica** [comment]
@tomcashman it is for an mmo, I just need to be able to send the actual node text to the frontend after some logic on it. And I figured others might need this too.

**Comment by tomcashman** [comment]
Makes sense to have this added.

I don't use public variables in the codebase so I'd like to keep the code consistent. It would be better to pass it to the [YarnNode constructor](https://github.com/mini2Dx/jarn/blob/master/jarn/src/main/java/org/mini2Dx/yarn/YarnNode.java#L43) and store is as a final variable similar to title + tags. Then access the content via a new method called getNodeContent().

**Comment by tymerica** [comment]
@tomcashman it is done!

**Comment by tomcashman** [comment]
1.1.2 is now on Maven Central :)

**Pull request merged**
